version: '3.7'

services:
  # Orthanc Database
  database:
    image: postgres:alpine
    container_name: pacsdb
    volumes:
      - ./orthanc/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=CnCuL2nS4yiUDm427L
      - POSTGRES_USER=orthanc
      - POSTGRES_DB=orthanc
    restart: always

  # Orthanc PACS
  pacs:
    image: jodogne/orthanc-plugins
    container_name: orthanc
    ports:
      - 8042:8042  # Orthanc Web Port
      - 4242:4242  # DICOM Port
    volumes:
      - ./orthanc/config:/etc/orthanc/:ro
      - ./orthanc/dicomImages:/var/lib/orthanc/db/
    restart: always
    environment:
      - PG_HOST=database
      - PG_USER=orthanc
      - PG_PASSWORD=CnCuL2nS4yiUDm427L
      - PG_DB=orthanc
    depends_on:
      - database

  # OHIF Viewer
  ohif:
    image: ohif/app
    container_name: ohif
    ports:
      - 3001:80  # OHIF Viewer Port
    volumes:
      - ./ohif/config/ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./ohif/config/logo.png:/usr/share/nginx/html/logo.png:ro

